language: php

matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env:
        - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
        - APCU_TEST=1
    - php: 7.3
    - php: 7.3
      env:
        - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
        - APCU_TEST=1
    - php: 7.4
    - php: 7.4
      env:
        - REPORT_EXIT_STATUS=1 NO_INTERACTION=1
        - APCU_TEST=1
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - echo "memory_limit=2G" >> $HOME/.phpenv/versions/`phpenv version-name`/etc/conf.d/travis.ni
  - phpize && ./configure && make

script:
  - if [ "${APCU_TEST}" ]; then cp $(php-config --extension-dir)/apcu.so modules/; sed -i 's/\$(PHP_TEST_SHARED_EXTENSIONS)/-d extension=apcu \$(PHP_TEST_SHARED_EXTENSIONS)/' Makefile; fi
  - make test TESTS="--show-diff" | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0

after_failure:
  - for FILE in `find ./tests -name '*.diff'`; do echo echo $FILE; cat $FILE; echo; done
